In [25]:
import sys
BASE_DIR = "../../.."
sys.path.insert(0, BASE_DIR)

BASE_DIR = "../../../../alexander_workspace/exp"
sys.path.insert(1, BASE_DIR)

import pandas as pd
import numpy as np
import ast
import random
import json
from time import time
import gc
import os
import joblib
import chromadb
from tqdm import tqdm
from dataclasses import dataclass, field
from sentence_transformers import SentenceTransformer
from typing import Dict, List
from dataclasses import dataclass
import pyarrow as pa

random.seed(42)

from src.agents.hosted import CustomAgent
from src.utils import ReaderMetrics

from embedder.ChromaConnector import (ChromaConnection, 
                                      VectorDBConnectionConfig, 
                                      VectorDBInstance)

CONTEXTS_DATASET_PATH = "../../../data/squadv2/contexts.csv"
QA_DATASET_PATH = "../../../data/squadv2/qa_dataset.csv"
AGENT_MODEL_PATH = "../../../models/Qwen/Qwen2.5-7B-Instruct" # "../../../models/Undi95/Meta-Llama-3-8B-Instruct-hf" | "../../../models/Qwen/Qwen2.5-7B-Instruct"

In [2]:
PARAMS = {
    'version': "3.2",
    'num_samples': 2000,
    'num_contexts': 15,
    'model': AGENT_MODEL_PATH,
    'system_prompt': "You are an AI assistant who helps solve user issues.",
    "item_format": "- [{score}] {document}",
    "user_prompt": 'Answer the question using the available information from the texts in the list below. Each text has a corresponding real-value score of its relevance to the question in square brackets at the beginning. Scores are ranged from 0.0 (the text is not suitable for generating an answer based on it) to 1.0 (the text is suitable for generating an answer based on it). Use this information. Choose texts with high enough relevance scores. If, based on the specified scores, there are no texts in the list that are relevant enough to generate answer based on them, then generate the following answer: "I do not have an answer to your question". Generate answer only in English. Do not duplicate the question in the answer. Generate only the answer to the specified question. Answer need to be short. Do not generate anything extra.',
    "prompt_format": "{user_p}\n\nAvailable information:\n{cnt_list}\n\nQuestion:\n{q}\n\nAnswer:\n",
    'gen_strat': {'max_new_tokens': 1024},
    'stub_answer': "I do not have an answer to your question",
    "scores_dataset_path": "/home/jovyan/work/alexander_workspace/exp/cosine_scores_squad2.csv",
    'vdb_context_info': {'path': "/home/jovyan/work/RAG-project-SMILES-2024-/data/squadv2/chroma/dbs/v3", 'db': {'db': 'squadv2', 'table': 'contexts'}},
    'vdb_query_info': {'path': "/home/jovyan/work/RAG-project-SMILES-2024-/data/squadv2/chroma/dbs/v3", 'db': {'db': 'squadv2', 'table': 'questions'}}
}

METADATA_SAVE_NAME = 'metadata.json'
USER_PROPMTS_SAVE_NAME = 'user_prompts.json'
PARAMS_SAVE_NAME = 'hyperp.json'
GEN_ANSW_SAVE_NAME = 'generation_info.json'
SCORES_SAVE_NAME = 'scores.json'
LOGS_SAVE_DIR = './logs'
META_INFO_DIR_NAME = 'gen_metainfo'

if os.path.exists(f'{LOGS_SAVE_DIR}/v{PARAMS["version"]}'):
    print("Dir exists")
else:
    print("Creating Dir...")
    os.mkdir(f'{LOGS_SAVE_DIR}/v{PARAMS["version"]}')
    os.mkdir(f'{LOGS_SAVE_DIR}/v{PARAMS["version"]}/{META_INFO_DIR_NAME}')

Creating Dir...

### Подключение к агенту

In [3]:
agent = CustomAgent(PARAMS['model'], output_logits=False, use_cache=True, output_attentions=False, output_scores=False, output_hidden_states=False)
output = agent.generate(user_prompt="what is wrong with humanity?", system_prompt=PARAMS['system_prompt'], gen_strategy=PARAMS['gen_strat'])
print(output[0])

Loading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]

The question of what is "wrong" with humanity is complex and multifaceted, as it can be interpreted in various ways. Here are a few perspectives:

1. **Conflict and Violence**: Throughout history, humans have engaged in wars, conflicts, and violence, often over resources, power, or beliefs.

2. **Environmental Degradation**: Many people believe that humanity's actions have led to significant environmental damage, including climate change, deforestation, pollution, and loss of biodiversity.

3. **Inequality**: There are persistent issues of inequality based on race, gender, socioeconomic status, and other factors, which lead to disparities in access to resources, opportunities, and justice.

4. **Moral Ambiguity**: Humans sometimes struggle with moral dilemmas and ethical behavior, leading to actions that harm others or the environment.

5. **Short-term Thinking**: Some argue that human societies often prioritize short-term gains over long-term sustainability and well-being.

6. **Psychological Issues**: Individual and collective psychological issues such as aggression, prejudice, and mental health problems can contribute to societal problems.

7. **Technological Impact**: The rapid development and deployment of technology can lead to unintended consequences, both positive and negative.

8. **Cultural and Social Norms**: Certain cultural and social norms can perpetuate harmful behaviors and attitudes.

It's important to note that while these issues exist, many individuals and groups are actively working towards solutions and improvements. Addressing these challenges requires a combination of education, policy changes, technological advancements, and shifts in cultural attitudes.

### Формируем список контекстов для каждого запроса со скорами

In [4]:
vdb_contexts_conf = VectorDBConnectionConfig(path=PARAMS['vdb_context_info']['path'], db_info=PARAMS['vdb_context_info']['db'])
connector_contexts = ChromaConnection(config=vdb_contexts_conf)
connector_contexts.count_items()

19029

In [5]:
vdb_query_conf = VectorDBConnectionConfig(path=PARAMS['vdb_query_info']['path'], db_info=PARAMS['vdb_query_info']['db'])
connector_query = ChromaConnection(config=vdb_query_conf)
print(connector_query.count_items())

86821

In [6]:
scores_df = pd.read_csv(PARAMS["scores_dataset_path"])
dataset_df = pd.read_csv(QA_DATASET_PATH)

In [7]:
scores_df

,query_id,contexts_ids,cos_dists
0,id0,"['id10', 'id0', 'id45', 'id53', 'id2', 'id26',...","[0.15416234731674194, 0.15581238269805908, 0.1..."
1,id1,"['id4', 'id0', 'id5', 'id3', 'id64', 'id50', '...","[0.15261220932006836, 0.16854727268218994, 0.1..."
2,id2,"['id10', 'id0', 'id1', 'id53', 'id12', 'id23',...","[0.13007789850234985, 0.13846325874328613, 0.1..."
3,id3,"['id8', 'id6114', 'id19', 'id6115', 'id6', 'id...","[0.16860461235046387, 0.17995333671569824, 0.1..."
4,id4,"['id84', 'id67', 'id13616', 'id94', 'id66', 'i...","[0.16440743207931519, 0.17258894443511963, 0.1..."
...,...,...,...
86816,id86816,"['id18973', 'id18917', 'id18932', 'id18934', '...","[0.11931037902832031, 0.1748185157775879, 0.18..."
86817,id86817,"['id3367', 'id3362', 'id3360', 'id3358', 'id16...","[0.18268996477127075, 0.18880540132522583, 0.1..."
86818,id86818,"['id18973', 'id18916', 'id18927', 'id18923', '...","[0.13600891828536987, 0.14367049932479858, 0.1..."
86819,id86819,"['id18973', 'id18917', 'id18934', 'id18924', '...","[0.1315150260925293, 0.16991901397705078, 0.17..."
86820,id86820,"['id225', 'id724', 'id14146', 'id15676', 'id11...","[0.20946866273880005, 0.21423524618148804, 0.2..."

In [8]:
dataset_df

,question,answer,relevant_context_id,metadata
0,When did Beyonce start becoming popular?,in the late 1990s,0,{'base_id': '56be85543aeaaa14008c9063'}
1,What areas did Beyonce compete in when she was...,singing and dancing,0,{'base_id': '56be85543aeaaa14008c9065'}
2,When did Beyonce leave Destiny's Child and bec...,2003,0,{'base_id': '56be85543aeaaa14008c9066'}
3,In what city and state did Beyonce grow up?,"Houston, Texas",0,{'base_id': '56bf6b0f3aeaaa14008c9601'}
4,In which decade did Beyonce become famous?,late 1990s,0,{'base_id': '56bf6b0f3aeaaa14008c9602'}
...,...,...,...,...
86816,In what US state did Kathmandu first establish...,Oregon,18973,{'base_id': '5735d259012e2f140011a09d'}
86817,What was Yangon previously known as?,Rangoon,18973,{'base_id': '5735d259012e2f140011a09e'}
86818,With what Belorussian city does Kathmandu have...,Minsk,18973,{'base_id': '5735d259012e2f140011a09f'}
86819,In what year did Kathmandu create its initial ...,1975,18973,{'base_id': '5735d259012e2f140011a0a0'}
86820,What is KMC an initialism of?,Kathmandu Metropolitan City,18973,{'base_id': '5735d259012e2f140011a0a1'}

In [9]:
CONTEXTS_LIST_IDS = []
for i in tqdm(range(PARAMS['num_samples'])):
    cur_scores = ast.literal_eval(scores_df['cos_dists'][i])
    cur_contexts = ast.literal_eval(scores_df['contexts_ids'][i])

    cur_list_ids = [(round(1-score, 5), cntx) for score, cntx in zip(cur_scores, cur_contexts)]
    
    CONTEXTS_LIST_IDS.append(cur_list_ids[:PARAMS['num_contexts']])

100%|██████████| 2000/2000 [00:00<00:00, 14742.88it/s]

In [10]:
CONTEXTS_LIST_IDS[0]

[(0.84584, 'id10'),
 (0.84419, 'id0'),
 (0.84188, 'id45'),
 (0.83928, 'id53'),
 (0.83849, 'id2'),
 (0.83739, 'id26'),
 (0.83638, 'id12'),
 (0.83603, 'id33'),
 (0.83575, 'id52'),
 (0.83561, 'id50'),
 (0.83555, 'id56'),
 (0.83433, 'id44'),
 (0.833, 'id11'),
 (0.83265, 'id47'),
 (0.82711, 'id14')]

### Готовим промпт

In [11]:
USER_PROMPTS = []
gc.collect()
for i in tqdm(range(len(CONTEXTS_LIST_IDS))):
    cur_question = connector_query.read([scores_df['query_id'][i]],includes=['documents'])[0].document
    documents_list = []
    for j in range(len(CONTEXTS_LIST_IDS[i])):
        cur_doc = connector_contexts.read([CONTEXTS_LIST_IDS[i][j][1]],includes=['documents'])[0].document
        cur_score = CONTEXTS_LIST_IDS[i][j][0]

        documents_list.append(PARAMS['item_format'].format(score=cur_score, document=cur_doc.strip()))

    documents_list = '\n'.join(documents_list)
    USER_PROMPTS.append(PARAMS['prompt_format'].format(user_p=PARAMS['user_prompt'], cnt_list=documents_list, q=cur_question))

100%|██████████| 2000/2000 [00:10<00:00, 186.07it/s]

In [12]:
with open(f"{LOGS_SAVE_DIR}/v{PARAMS['version']}/{USER_PROPMTS_SAVE_NAME}", 'w', encoding='utf-8') as fp:
    fp.write(json.dumps(USER_PROMPTS, ensure_ascii=False, indent=1))

# сохраняем конфигурацию эксперимента
with open(f"{LOGS_SAVE_DIR}/v{PARAMS['version']}/{PARAMS_SAVE_NAME}", 'w', encoding='utf-8') as fp:
    fp.write(json.dumps(PARAMS, ensure_ascii=False, indent=1))

In [13]:
print(USER_PROMPTS[0])

Answer the question using the available information from the texts in the list below. Each text has a corresponding real-value score of its relevance to the question in square brackets at the beginning. Scores are ranged from 0.0 (the text is not suitable for generating an answer based on it) to 1.0 (the text is suitable for generating an answer based on it). Use this information. Choose texts with high enough relevance scores. If, based on the specified scores, there are no texts in the list that are relevant enough to generate answer based on them, then generate the following answer: "I do not have an answer to your question". Generate answer only in English. Do not duplicate the question in the answer. Generate only the answer to the specified question. Answer need to be short. Do not generate anything extra.

Available information:
- [0.84584] Beyoncé's first solo recording was a feature on Jay Z's "'03 Bonnie & Clyde" that was released in October 2002, peaking at number four on the U.S. Billboard Hot 100 chart. Her first solo album Dangerously in Love was released on June 24, 2003, after Michelle Williams and Kelly Rowland had released their solo efforts. The album sold 317,000 copies in its first week, debuted atop the Billboard 200, and has since sold 11 million copies worldwide. The album's lead single, "Crazy in Love", featuring Jay Z, became Beyoncé's first number-one single as a solo artist in the US. The single "Baby Boy" also reached number one, and singles, "Me, Myself and I" and "Naughty Girl", both reached the top-five. The album earned Beyoncé a then record-tying five awards at the 46th Annual Grammy Awards; Best Contemporary R&B Album, Best Female R&B Vocal Performance for "Dangerously in Love 2", Best R&B Song and Best Rap/Sung Collaboration for "Crazy in Love", and Best R&B Performance by a Duo or Group with Vocals for "The Closer I Get to You" with Luther Vandross.
- [0.84419] Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ bee-YON-say) (born September 4, 1981) is an American singer, songwriter, record producer and actress. Born and raised in Houston, Texas, she performed in various singing and dancing competitions as a child, and rose to fame in the late 1990s as lead singer of R&B girl-group Destiny's Child. Managed by her father, Mathew Knowles, the group became one of the world's best-selling girl groups of all time. Their hiatus saw the release of Beyoncé's debut album, Dangerously in Love (2003), which established her as a solo artist worldwide, earned five Grammy Awards and featured the Billboard Hot 100 number-one singles "Crazy in Love" and "Baby Boy".
- [0.84188] In September 2010, Beyoncé made her runway modelling debut at Tom Ford's Spring/Summer 2011 fashion show. She was named "World's Most Beautiful Woman" by People and the "Hottest Female Singer of All Time" by Complex in 2012. In January 2013, GQ placed her on its cover, featuring her atop its "100 Sexiest Women of the 21st Century" list. VH1 listed her at number 1 on its 100 Sexiest Artists list. Several wax figures of Beyoncé are found at Madame Tussauds Wax Museums in major cities around the world, including New York, Washington, D.C., Amsterdam, Bangkok, Hollywood and Sydney.
- [0.83928] Beyoncé has received numerous awards. As a solo artist she has sold over 15 million albums in the US, and over 118 million records worldwide (a further 60 million additionally with Destiny's Child), making her one of the best-selling music artists of all time. The Recording Industry Association of America (RIAA) listed Beyoncé as the top certified artist of the 2000s, with a total of 64 certifications. Her songs "Crazy in Love", "Single Ladies (Put a Ring on It)", "Halo", and "Irreplaceable" are some of the best-selling singles of all time worldwide. In 2009, The Observer named her the Artist of the Decade and Billboard named her the Top Female Artist and Top Radio Songs Artist of the Decade. In 2010, Billboard named her in their "Top 50 R&B/Hip-Hop Artists of the Past 25 Years" list at number 15. In 2012 VH1 ranked her third on their list of the "100 Greatest Women in Music". Beyoncé was the first female artist to be honored with the International Artist Award at the American Music Awards. She has also received the Legend Award at the 2008 World Music Awards and the Billboard Millennium Award at the 2011 Billboard Music Awards.
- [0.83849] A self-described "modern-day feminist", Beyoncé creates songs that are often characterized by themes of love, relationships, and monogamy, as well as female sexuality and empowerment. On stage, her dynamic, highly choreographed performances have led to critics hailing her as one of the best entertainers in contemporary popular music. Throughout a career spanning 19 years, she has sold over 118 million records as a solo artist, and a further 60 million with Destiny's Child, making her one of the best-selling music artists of all time. She has won 20 Grammy Awards and is the most nominated woman in the award's history. The Recording Industry Association of America recognized her as the Top Certified Artist in America during the 2000s decade. In 2009, Billboard named her the Top Radio Songs Artist of the Decade, the Top Female Artist of the 2000s and their Artist of the Millennium in 2011. Time listed her among the 100 most influential people in the world in 2013 and 2014. Forbes magazine also listed her as the most powerful female musician of 2015.
- [0.83739] Beyoncé is believed to have first started a relationship with Jay Z after a collaboration on "'03 Bonnie & Clyde", which appeared on his seventh album The Blueprint 2: The Gift & The Curse (2002). Beyoncé appeared as Jay Z's girlfriend in the music video for the song, which would further fuel speculation of their relationship. On April 4, 2008, Beyoncé and Jay Z were married without publicity. As of April 2014, the couple have sold a combined 300 million records together. The couple are known for their private relationship, although they have appeared to become more relaxed in recent years. Beyoncé suffered a miscarriage in 2010 or 2011, describing it as "the saddest thing" she had ever endured. She returned to the studio and wrote music in order to cope with the loss. In April 2011, Beyoncé and Jay Z traveled to Paris in order to shoot the album cover for her 4, and unexpectedly became pregnant in Paris.
- [0.83638] Beyoncé's second solo album B'Day was released on September 5, 2006, in the US, to coincide with her twenty-fifth birthday. It sold 541,000 copies in its first week and debuted atop the Billboard 200, becoming Beyoncé's second consecutive number-one album in the United States. The album's lead single "Déjà Vu", featuring Jay Z, reached the top five on the Billboard Hot 100 chart. The second international single "Irreplaceable" was a commercial success worldwide, reaching number one in Australia, Hungary, Ireland, New Zealand and the United States. B'Day also produced three other singles; "Ring the Alarm", "Get Me Bodied", and "Green Light" (released in the United Kingdom only).
- [0.83603] Forbes magazine began reporting on Beyoncé's earnings in 2008, calculating that the $80 million earned between June 2007 to June 2008, for her music, tour, films and clothing line made her the world's best-paid music personality at the time, above Madonna and Celine Dion. They placed her fourth on the Celebrity 100 list in 2009 and ninth on the "Most Powerful Women in the World" list in 2010. The following year, Forbes placed her eighth on the "Best-Paid Celebrities Under 30" list, having earned $35 million in the past year for her clothing line and endorsement deals. In 2012, Forbes placed Beyoncé at number 16 on the Celebrity 100 list, twelve places lower than three years ago yet still having earned $40 million in the past year for her album 4, clothing line and endorsement deals. In the same year, Beyoncé and Jay Z placed at number one on the "World's Highest-Paid Celebrity Couples", for collectively earning $78 million. The couple made it into the previous year's Guinness World Records as the "highest-earning power couple" for collectively earning $122 million in 2009. For the years 2009 to 2011, Beyoncé earned an average of $70 million per year, and earned $40 million in 2012. In 2013, Beyoncé's endorsements of Pepsi and H&M made her and Jay Z the world's first billion dollar couple in the music industry. That year, Beyoncé was published as the fourth most-powerful celebrity in the Forbes rankings. MTV estimated that by the end of 2014, Beyoncé would become the highest-paid black musician in history; she succeeded to do so in April 2014. In June 2014, Beyoncé ranked at #1 on the Forbes Celebrity 100 list, earning an estimated $115 million throughout June 2013 – June 2014. This in turn was the first time she had topped the Celebrity 100 list as well as being her highest yearly earnings to date. As of May 2015, her net worth is estimated to be $250 million.
- [0.83575] Her debut single, "Crazy in Love" was named VH1's "Greatest Song of the 2000s", NME's "Best Track of the 00s" and "Pop Song of the Century", considered by Rolling Stone to be one of the 500 greatest songs of all time, earned two Grammy Awards and is one of the best-selling singles of all time at around 8 million copies. The music video for "Single Ladies (Put a Ring on It)", which achieved fame for its intricate choreography and its deployment of jazz hands, was credited by the Toronto Star as having started the "first major dance craze of both the new millennium and the Internet", triggering a number of parodies of the dance choreography and a legion of amateur imitators on YouTube. In 2013, Drake released a single titled "Girls Love Beyoncé", which featured an interpolation from Destiny Child's "Say My Name" and discussed his relationship with women. In January 2012, research scientist Bryan Lessard named Scaptia beyonceae, a species of horse fly found in Northern Queensland, Australia after Beyoncé due to the fly's unique golden hairs on its abdomen. In July 2014, a Beyoncé exhibit was introduced into the "Legends of Rock" section of the Rock and Roll Hall of Fame. The black leotard from the "Single Ladies" video and her outfit from the Super Bowl half time performance are among several pieces housed at the museum.
- [0.83561] In The New Yorker music critic Jody Rosen described Beyoncé as "the most important and compelling popular musician of the twenty-first century..... the result, the logical end point, of a century-plus of pop." When The Guardian named her Artist of the Decade, Llewyn-Smith wrote, "Why Beyoncé? [...] Because she made not one but two of the decade's greatest singles, with Crazy in Love and Single Ladies (Put a Ring on It), not to mention her hits with Destiny's Child; and this was the decade when singles – particularly R&B singles – regained their status as pop's favourite medium. [...] [She] and not any superannuated rock star was arguably the greatest live performer of the past 10 years." In 2013, Beyoncé made the Time 100 list, Baz Luhrmann writing "no one has that voice, no one moves the way she moves, no one can hold an audience the way she does... When Beyoncé does an album, when Beyoncé sings a song, when Beyoncé does anything, it's an event, and it's broadly influential. Right now, she is the heir-apparent diva of the USA — the reigning national voice." In 2014, Beyoncé was listed again on the Time 100 and also featured on the cover of the issue.
- [0.83555] Beyoncé has worked with Tommy Hilfiger for the fragrances True Star (singing a cover version of "Wishing on a Star") and True Star Gold; she also promoted Emporio Armani's Diamonds fragrance in 2007. Beyoncé launched her first official fragrance, Heat in 2010. The commercial, which featured the 1956 song "Fever", was shown after the water shed in the United Kingdom as it begins with an image of Beyoncé appearing to lie naked in a room. In February 2011, Beyoncé launched her second fragrance, Heat Rush. Beyoncé's third fragrance, Pulse, was launched in September 2011. In 2013, The Mrs. Carter Show Limited Edition version of Heat was released. The six editions of Heat are the world's best-selling celebrity fragrance line, with sales of over $400 million.
- [0.83433] Beyoncé has been described as a having a wide-ranging sex appeal, with music journalist Touré writing that since the release of Dangerously in Love, she has "become a crossover sex symbol". Offstage Beyoncé says that while she likes to dress sexily, her onstage dress "is absolutely for the stage." Due to her curves and the term's catchiness, in the 2000s, the media often used the term "Bootylicious" (a portmanteau of the words booty and delicious) to describe Beyoncé, the term popularized by Destiny's Child's single of the same name. In 2006, it was added to the Oxford English Dictionary.
- [0.833] In November 2003, she embarked on the Dangerously in Love Tour in Europe and later toured alongside Missy Elliott and Alicia Keys for the Verizon Ladies First Tour in North America. On February 1, 2004, Beyoncé performed the American national anthem at Super Bowl XXXVIII, at the Reliant Stadium in Houston, Texas. After the release of Dangerously in Love, Beyoncé had planned to produce a follow-up album using several of the left-over tracks. However, this was put on hold so she could concentrate on recording Destiny Fulfilled, the final studio album by Destiny's Child. Released on November 15, 2004, in the US and peaking at number two on the Billboard 200, Destiny Fulfilled included the singles "Lose My Breath" and "Soldier", which reached the top five on the Billboard Hot 100 chart. Destiny's Child embarked on a worldwide concert tour, Destiny Fulfilled... and Lovin' It and during the last stop of their European tour, in Barcelona on June 11, 2005, Rowland announced that Destiny's Child would disband following the North American leg of the tour. The group released their first compilation album Number 1's on October 25, 2005, in the US and accepted a star on the Hollywood Walk of Fame in March 2006.
- [0.83265] The Bey Hive is the name given to Beyoncé's fan base. Fans were previously titled "The Beyontourage", (a portmanteau of Beyoncé and entourage). The name Bey Hive derives from the word beehive, purposely misspelled to resemble her first name, and was penned by fans after petitions on the online social networking service Twitter and online news reports during competitions.
- [0.82711] On April 4, 2008, Beyoncé married Jay Z. She publicly revealed their marriage in a video montage at the listening party for her third studio album, I Am... Sasha Fierce, in Manhattan's Sony Club on October 22, 2008. I Am... Sasha Fierce was released on November 18, 2008 in the United States. The album formally introduces Beyoncé's alter ego Sasha Fierce, conceived during the making of her 2003 single "Crazy in Love", selling 482,000 copies in its first week, debuting atop the Billboard 200, and giving Beyoncé her third consecutive number-one album in the US. The album featured the number-one song "Single Ladies (Put a Ring on It)" and the top-five songs "If I Were a Boy" and "Halo". Achieving the accomplishment of becoming her longest-running Hot 100 single in her career, "Halo"'s success in the US helped Beyoncé attain more top-ten singles on the list than any other woman during the 2000s. It also included the successful "Sweet Dreams", and singles "Diva", "Ego", "Broken-Hearted Girl" and "Video Phone". The music video for "Single Ladies" has been parodied and imitated around the world, spawning the "first major dance craze" of the Internet age according to the Toronto Star. The video has won several awards, including Best Video at the 2009 MTV Europe Music Awards, the 2009 Scottish MOBO Awards, and the 2009 BET Awards. At the 2009 MTV Video Music Awards, the video was nominated for nine awards, ultimately winning three including Video of the Year. Its failure to win the Best Female Video category, which went to American country pop singer Taylor Swift's "You Belong with Me", led to Kanye West interrupting the ceremony and Beyoncé improvising a re-presentation of Swift's award during her own acceptance speech. In March 2009, Beyoncé embarked on the I Am... World Tour, her second headlining worldwide concert tour, consisting of 108 shows, grossing $119.5 million.

Question:
When did Beyonce start becoming popular?

Answer:

In [14]:
del scores_df
gc.collect()

66

### Генерируем ответы на вопросы

In [15]:
generate_answers = []
display_iter = 100
s_time = time()
for i in tqdm(range(len(USER_PROMPTS))):
    pred_answer, meta_info = agent.generate(user_prompt=USER_PROMPTS[i], system_prompt=PARAMS['system_prompt'], gen_strategy=PARAMS['gen_strat'])
    generate_answers.append(pred_answer)

    # logits = torch.cat(metainfo['logits'], 0).cpu().detach().numpy()
    # logits_int8 = logits.astype('int8') 
    # token_logits = {f"token_{i}": token_logits for i, token_logits in enumerate(logits_int8)}
    # pa_table = pa.table(token_logits)
    # pa.parquet.write_table(pa_table, f"{LOGS_SAVE_DIR}/v{PARAMS['version']}/{META_INFO_DIR_NAME}/logits_{i}.parquet")
    
    if i % display_iter == 0:
        print(f"\n[{i}]: \nGEN: {pred_answer}\nGOLD: {dataset_df['answer'][i]}")
e_time = time()

  0%|          | 1/2000 [00:02<1:08:43,  2.06s/it]

[0]:
GEN: Beyoncé started becoming popular after the release of her first solo album, Dangerously in Love, in 2003.
GOLD: in the late 1990s

  5%|▌         | 101/2000 [02:04<36:20,  1.15s/it]

[100]:
GEN: I do not have an answer to your question.
GOLD: eleven

 10%|█         | 201/2000 [04:04<34:18,  1.14s/it]

[200]:
GEN: I do not have an answer to your question.
GOLD: ten

 15%|█▌        | 301/2000 [06:04<33:41,  1.19s/it]

[300]:
GEN: I do not have an answer to your question.
GOLD: Beck

 20%|██        | 401/2000 [07:59<30:15,  1.14s/it]

[400]:
GEN: I do not have an answer to your question.
GOLD: Forbes

 25%|██▌       | 501/2000 [09:59<29:09,  1.17s/it]

[500]:
GEN: I do not have an answer to your question.
GOLD: Jarett Wieselman

 30%|███       | 601/2000 [12:02<26:52,  1.15s/it]

[600]:
GEN: I do not have an answer to your question.
GOLD: 8 million

 35%|███▌      | 701/2000 [14:04<24:15,  1.12s/it]

[700]:
GEN: I do not have an answer to your question.
GOLD: in Destiny's Child's shows and tours

 40%|████      | 801/2000 [16:06<27:16,  1.36s/it]

[800]:
GEN: I do not have an answer to your question.
GOLD: Polish

 45%|████▌     | 901/2000 [17:59<20:15,  1.11s/it]

[900]:
GEN: I do not have an answer to your question.
GOLD: Rondo Op. 1.

 50%|█████     | 1001/2000 [19:44<17:19,  1.04s/it]

[1000]:
GEN: I do not have an answer to your question.
GOLD: Polish

 55%|█████▌    | 1101/2000 [21:29<14:52,  1.01it/s]

[1100]:
GEN: I do not have an answer to your question.
GOLD: Pleyel

 60%|██████    | 1201/2000 [23:21<15:03,  1.13s/it]

[1200]:
GEN: I do not have an answer to your question.
GOLD: 1830

 65%|██████▌   | 1301/2000 [25:17<14:32,  1.25s/it]

[1300]:
GEN: I do not have an answer to your question.
GOLD: Clésinger

 70%|███████   | 1401/2000 [27:14<11:10,  1.12s/it]

[1400]:
GEN: I do not have an answer to your question.
GOLD: Karol Szymanowski

 75%|███████▌  | 1501/2000 [29:15<10:40,  1.28s/it]

[1500]:
GEN: I do not have an answer to your question.
GOLD: disciples

 80%|████████  | 1601/2000 [31:15<07:53,  1.19s/it]

[1600]:
GEN: I do not have an answer to your question.
GOLD: Kublai

 85%|████████▌ | 1701/2000 [33:18<06:16,  1.26s/it]

[1700]:
GEN: I do not have an answer to your question.
GOLD: Altan Khan

 90%|█████████ | 1801/2000 [35:11<03:50,  1.16s/it]

[1800]:
GEN: I do not have an answer to your question.
GOLD: IXI

 95%|█████████▌| 1901/2000 [37:08<01:43,  1.05s/it]

[1900]:
GEN: I do not have an answer to your question.
GOLD: September 12, 2006

100%|██████████| 2000/2000 [39:02<00:00,  1.17s/it]

In [16]:
# сохраняем используемые контексты + сгнерированные ответы
gen_info = []
for i in range(PARAMS['num_samples']):
    formated_contexts = [(float(item[0]), item[1]) for item in CONTEXTS_LIST_IDS[i]]
    cur_item = {'gen_answer': str(generate_answers[i]), 'used_contexts': formated_contexts}
    gen_info.append(cur_item)

with open(f"{LOGS_SAVE_DIR}/v{PARAMS['version']}/{GEN_ANSW_SAVE_NAME}", 'w', encoding='utf-8') as fp:
    fp.write(json.dumps(gen_info, ensure_ascii=False, indent=1))

with open(f"{LOGS_SAVE_DIR}/v{PARAMS['version']}/{METADATA_SAVE_NAME}", 'w', encoding='utf-8') as fp:
    fp.write(json.dumps({'elapsed_time': e_time - s_time}, ensure_ascii=False, indent=1))

### Оцениваем качество

In [17]:
LOADING_VERSION = "3.2"

In [18]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /home/jovyan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /home/jovyan/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [19]:
with open(f'{LOGS_SAVE_DIR}/v{LOADING_VERSION}/{GEN_ANSW_SAVE_NAME}','r', encoding='utf8') as fd:
    predicted_answers = list(map(lambda v: v['gen_answer'], json.loads(fd.read())))

In [20]:
metrics = ReaderMetrics(base_dir="../../..", model_path='en_electra_base')

Loading Meteor...
Loading ExactMatch

In [21]:
dataset_df = pd.read_csv(QA_DATASET_PATH)

In [22]:
target_scores = {
    'BLEU2': [], 'BLEU1': [],
    'ExactMatch': [],'METEOR': [],
    'BertScore': [],
    'Levenshtain': [],
    'ROUGEL': []}

stub_scores = {
    'BLEU2': [], 'BLEU1': [],
    'ExactMatch': [],'METEOR': [],
    'BertScore': [],
    'Levenshtain': [],
    'ROUGEL': []}

show_step = 50

process = tqdm(range(PARAMS['num_samples']))
target_answers =  dataset_df['answer'].to_list()[:PARAMS['num_samples']]
tmp_stub_pred_answers = []
for i in process:
    
    predicted_answer = predicted_answers[i]
    target_answer = target_answers[i]

    target_scores['BLEU1'] += metrics.bleu1([predicted_answer], [target_answer])
    target_scores['BLEU2'] += metrics.bleu2([predicted_answer], [target_answer])
    target_scores['ExactMatch'] += metrics.exact_match([predicted_answer], [target_answer])
    target_scores['METEOR'] += metrics.meteor([predicted_answer], [target_answer])
    target_scores['Levenshtain'] += metrics.levenshtain_score([predicted_answer], [target_answer])
    target_scores['ROUGEL'] += metrics.rougel([predicted_answer], [target_answer])

    stub_pred_answer = predicted_answer
    tmp_stub_pred_answers.append(stub_pred_answer)
    
    stub_scores['BLEU1'] += metrics.bleu1([stub_pred_answer], [PARAMS['stub_answer']])
    stub_scores['BLEU2'] += metrics.bleu2([stub_pred_answer], [PARAMS['stub_answer']])
    stub_scores['ExactMatch'] += metrics.exact_match([stub_pred_answer], [PARAMS['stub_answer']])
    stub_scores['METEOR'] += metrics.meteor([stub_pred_answer], [PARAMS['stub_answer']])
    stub_scores['Levenshtain'] += metrics.levenshtain_score([stub_pred_answer], [PARAMS['stub_answer']])
    stub_scores['ROUGEL'] += metrics.rougel([stub_pred_answer], [PARAMS['stub_answer']])
            
    if i % show_step == 0:
        process.set_postfix({m_name: np.mean(score) for m_name, score in stub_scores.items()})

target_scores = {m_name: round(float(np.mean(score)), 5) for m_name, score in target_scores.items()}
target_scores['BertScore'] = metrics.bertscore(predicted_answers, target_answers)

stub_scores = {m_name: round(float(np.mean(score)), 5) for m_name, score in stub_scores.items()}
stub_scores['BertScore'] = metrics.bertscore(tmp_stub_pred_answers, [PARAMS['stub_answer']]*len(tmp_stub_pred_answers))
stub_scores['elapsed_time_sec'] = round(float(process.format_dict["elapsed"]), 3)

/home/jovyan/work/alexander_workspace/conda/rag_alex/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/jovyan/work/alexander_workspace/conda/rag_alex/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 2000/2000 [05:43<00:00,  5.82it/s, BLEU2=0.867, BLEU1=0.874, ExactMatch=0.983, METEOR=0.972, BertScore=nan, Levenshtain=2.4, ROUGEL=0.983]

In [23]:
LOADING_VERSION

'3.2'

In [24]:
with open(f"{LOGS_SAVE_DIR}/v{LOADING_VERSION}/{SCORES_SAVE_NAME}", 'w', encoding='utf-8') as fp:
    fp.write(json.dumps({'target_answers': target_scores, 'stub_answers': stub_scores}, ensure_ascii=False, indent=1))

### Смотрим: встречается ли релевантный контекст

In [26]:
dataset_df = pd.read_csv(QA_DATASET_PATH)
scores_df = pd.read_csv(PARAMS["scores_dataset_path"])

In [31]:
rel_cntx_ids = dataset_df['relevant_context_id'][:PARAMS['num_samples']].tolist()

In [35]:
retrieved_cntx_ids = list(map(lambda item: ast.literal_eval(item), scores_df['contexts_ids'][:PARAMS['num_samples']]))
retrieved_cntx_ids = list(map(lambda items: list(map(lambda item: int(item[2:]), items)), retrieved_cntx_ids))

In [40]:
true_cnt_exist = [true_id in retr_ids for true_id ,retr_ids in zip(rel_cntx_ids, retrieved_cntx_ids)]

In [45]:
sum(true_cnt_exist)

16