In [15]:
import os
from run_judgement import PipelineArguments, run_pipeline

In [16]:
import pandas as pd

df_path = "squad_v2/results/squadv2_answer_labeling_lmjudged_raw_1_3_2_2.csv"
df_judged = pd.read_csv(df_path)
df_judged.tail()

                                       model_assessment
1878  Based on the question "In what year did airlin...
1879  To evaluate the generated answer, let's compar...
1880  Based on the question "Which product enabled u...
1881  To evaluate the generated answer, let's compar...
1882  Based on the question "What does DRM stand for...

In [18]:
df_judged.iloc[0].model_assessment

'To evaluate the generated answer, let\'s compare it to the ground truth answer while considering the question "When did Beyonce start becoming popular?"\n\n**Ground truth answer:** "in the late 1990s"\n\n**Generated answer:** "Beyoncé started becoming a solo artist worldwide in the late 1990s after the hiatus of Destiny\'s Child. Her debut album \'Dangerously in Love\' in 2003 further established her popularity."\n\nThe generated answer correctly identifies that Beyoncé started becoming popular in the late 1990s, which matches the ground truth answer. The additional information about her debut album and the hiatus of Destiny\'s Child does not contradict the ground truth answer but rather provides more context.\n\n**Model score:** 1'

In [19]:
df_judged.iloc[1865].model_assessment

'Based on the provided information, let\'s evaluate the generated answer:\n\nQuestion: "In what year did Apple reveal that it would provide compatibility with a wide range of auto manufacturers?"\nGround truth answer: "2005"\nGenerated answer: "2005"\n\nSince the generated answer matches the ground truth answer exactly and correctly responds to the interrogative word "when" with a year, the model score is:\n\nModel score: 1'

In [11]:
df_judged = df_judged.dropna()

In [12]:
df_judged.shape

(1865, 1)

In [13]:
df_judged.tail()

                                       model_assessment
1860  Based on the question "What are six companies ...
1861  Based on the question "What can A/V cables be ...
1862  Based on the question "Who manufactures a pedo...
1863  Based on the question "Which company manufactu...
1864  Based on the question "What company was first ...

In [14]:
df_judged.to_csv(df_path, index=False)

In [4]:
df_judged.iloc[2]["model_assessment"]

'To evaluate the quality of the generated answer, let\'s compare it with the ground truth answer while considering the question.\n\n**Question:** "When did Beyonce leave Destiny\'s Child and become a solo singer?"\n\n**Ground truth answer:** "2003"\n\n**Generated answer:** "Beyoncé left Destiny\'s Child and became a solo artist around 2003 when her debut album \'Dangerously in Love\' was released."\n\nThe question asks "when," which means the answer should include a specific time or date. The ground truth answer provides the year "2003." The generated answer also includes the year "2003" and provides additional context about Beyoncé\'s debut album.\n\nSince the generated answer correctly states the year 2003, it meets the criteria for answering the "when" question.\n\n**Model score:** 1'

In [2]:
logs_dir = "/home/jovyan/work/alexander_workspace/exp/squad_v2/results"
save_prefix = "lmjudged_raw"
prefix = "squadv2_answer_labeling"
api_key_path = "../mistral_api_key_2"
prompt_ending = "Model score:"
gen_args_path = "/home/jovyan/work/alexander_workspace/exp/squad_v2/configs/gen_args.json"
exp_nums = [
    "1_1_1_2",
    "1_1_2_1",
    "1_1_2_2",
    "1_1_3_1",
    "1_1_3_2",
    "1_2_1_2",
    "1_2_2_1",
    "1_2_2_2",
    "1_2_3_1",
    "1_2_3_2",
    "1_3_1_2",
    "1_3_2_1",
    "1_3_2_2",
    "1_3_3_1",
    "1_3_3_2",
    "4_1_1_2",
    "4_1_2_1",
    "4_1_2_2",
    "4_1_3_1",
    "4_1_3_2"
]

In [ ]:
for exp_num in exp_nums:
    data_path = os.path.join(logs_dir, prefix + "_" + exp_num + ".csv")
    save_path = os.path.join(logs_dir, prefix + "_" + save_prefix + "_" + exp_num + ".csv")
    args = PipelineArguments(
        data_path=data_path,
        save_path=save_path,
        api_key_path=api_key_path,
        prompt_ending=prompt_ending,
        gen_args_path=gen_args_path
    )
    run_pipeline(args)